apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: game-webapp
    replicas: "3"
  name: game-webapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: game-webapp
      replicas: "3"
  template:
    metadata:
      labels:
        app: game-webapp
        replicas: "3"
    spec:
      containers:
      - image: emogaka/game-web-server:latest
        name: game-webapp
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
