apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Common labels for all resources
commonLabels:
  app: game-webapp
  replicas: "3"

resources:
- ./deployment.yaml

images:
- name: emogaka/game-web-server
  newName: emogaka/game-web-server
  newTag: latest